language: r

install:
    - Rscript install.R

script:
    - Rscript script.R

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: data.csv
  skip_cleanup: true
  on:
    tags: true




#env:
#  global:
#    - issue=$(<issues.txt)
#matrix:
#  include:
#  - language: bash
#    script:
#    - bash run.sh 