language: r

install:
    - Rscript install.R

script:
    - Rscript script.R

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "relund"
  - git config --local user.email "junk@relund.dk"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
      
deploy:
  provider: releases
  github_token: $github_token
  file: data.csv
  skip_cleanup: true
  overwrite: true




#env:
#  global:
#    - issue=$(<issues.txt)
#matrix:
#  include:
#  - language: bash
#    script:
#    - bash run.sh 